<!DOCTYPE html>
<html>
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <title><?php echo SITE_NAME; ?></title>
	    
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	    <meta name="apple-mobile-web-app-capable" content="yes" />	    

	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/html5shiv.js"></script>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/respond.min.js"></script>
		<![endif]-->	      	    
	    
	 	<?php
			if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ) {
	 			$currentTheme = ( strlen( @$_COOKIE['theme'] ) ) ? $_COOKIE['theme'] : SITE_DEFAULT_TEMPLATE;
			} else {
	 			$currentTheme = SITE_DEFAULT_TEMPLATE;
	 			setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
			}
			
			$_SESSION['current_theme'] = $currentTheme;
		?> 
		
		<?php $siteThemes		= $GLOBALS['SITE_THEMES']; ?>
		<?php $bootstrapThemes	= $GLOBALS['BOOTSTRAP_THEMES']; ?>    	 
				
		<?php if( !empty( $siteThemes ) ): ?>
			
			<?php 		
				if( $currentTheme != SITE_DEFAULT_TEMPLATE ) {
					if( !array_key_exists( $currentTheme, $siteThemes ) ) {
						$currentTheme = SITE_DEFAULT_TEMPLATE;
						setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
					}
				}
			?>
						
			<script type="text/javascript">	
				var BOOTSTRAP_THEMES	= new Array();	
				var SITE_THEMES			= new Array();
				
				<?php foreach( $siteThemes AS $key => $value ): ?>
					SITE_THEMES['<?php echo $key; ?>'] = '<?php echo $value['display_name']; ?>';	
				<?php endforeach; ?>

				<?php foreach( $bootstrapThemes AS $key => $value ): ?>
					BOOTSTRAP_THEMES['<?php echo $key; ?>'] = '<?php echo $value['display_name']; ?>';
				<?php endforeach; ?>				
			</script>
			<?php else: ?>
			<script type="text/javascript">		
				var BOOTSTRAP_THEMES	= new Array();
				var SITE_THEMES			= new Array();
			</script>			
		<?php endif; ?>
		
	    <?php if( !empty( $_SESSION['site']['phrases'] ) ): ?>    
	    	<script type="text/javascript">
	    		var SITE_PHRASES = new Array();
				<?php foreach( $_SESSION['site']['phrases'] AS $key => $value ): ?>
					SITE_PHRASES['<?php echo $key; ?>'] = '<?php echo addslashes( str_replace( "\r\n", '<br>', $value ) ); ?>';
				<?php endforeach; ?>
	    	</script>
	    <?php endif; ?>	
	    
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/phpjs.js"></script>	    		   	    
		<script type="text/javascript">
			var BASEURL					= '<?php echo PROTOCOL_RELATIVE_URL; ?>';
			var DEFAULT_PRELOADER_IMAGE	= '<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>';
			var CURRENT_THEME 			= '<?php echo $currentTheme; ?>';
			var CURRENT_USERNAME		= '<?php echo $_SESSION['user']['username']; ?>';
			var SITE_NAME				= '<?php echo SITE_NAME; ?>';		
			var CURRENT_USER			= new Array();
			var UUID					= uuid();		
			var USE_BLOCKUI				= <?php echo (int)SITE_USE_BLOCKUI; ?>;
			var IS_MOBILE				= <?php echo (int)IS_MOBILE; ?>;	
					
			<?php foreach( $_SESSION['user'] AS $key => $value ): ?>
				<?php if( !is_array( $value ) ): ?>
				    CURRENT_USER['<?php echo $key; ?>'] = '<?php echo base64_encode( $value ); ?>';
				<?php endif; ?>
			<?php endforeach; ?>
		</script>     
	
	    <meta name="robots" content="noimageindex" />
	    
	    <!-- START:    Favicon -->
	    <link rel="Shortcut Icon" type="image/x-icon" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/favicon.ico" /><base>
        <link rel="apple-touch-icon" sizes="57x57" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/favicon-16x16.png">
        <link rel="manifest" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">	    
	    <!-- END:      Favicon -->
	        
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-1.9.1.min.js"></script>					
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootstrap.min.js"></script>		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.cookie.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-ui-1.9.2.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jstorage.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.imgpreload.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/imagesloaded.pkgd.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.defaults.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.observor.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/custom.js"></script>
		
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/custom.css" type="text/css" />				
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/font-awesome.min.css">
		
		<!-- jQuery UI -->
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/jquery-ui/themes/base/jquery-ui.css">
			    
	    <link rel="stylesheet" id="bootstrapCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/bootstrap.min.css">
        <link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/bootstrap.min.css" rel="stylesheet">									     
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/homepage.css" type="text/css" />	
	    		
		<!-- SmartMenus -->
		<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/extensions/smartmenus/jquery.smartmenus.bootstrap.css" rel="stylesheet">	    
	    
	    <!-- Sticky Footer -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/sticky-footer-navbar.css" type="text/css" />	
	    
	    <!-- Custom CSS (OpenFace) -->	
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/openface.css" type="text/css" />		    
	    
	    <!-- Custom CSS -->	
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/newsfeed.css" type="text/css" />	
	    
	    <!-- scrollUp -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/scrollUp.css" />
	    
	    <?php
	        switch( $currentTheme ) {
	            case 'faceboot':
	    ?>
	    
	    <!-- Custom CSS (Faceboot) -->	
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/extensions.min.css" type="text/css" />	
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/app.min.css" type="text/css" />
	    
	    <?php
	                break;
	        }
	    ?>	
	    
        <!-- Bootstrap Datepicker -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/extensions/bootstrap-datepicker/bootstrap-datepicker3.min.css" type="text/css">						     
	</head>

	<body>
		<!-- START:		blockUI -->
		<?php if( (int)SITE_USE_BLOCKUI == 1 AND (int)IS_MOBILE != 1 ): ?>
			<div style="display: block" class="blockUI"></div>
			<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(255, 255, 255); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
			<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?></div>
		<?php endif; ?>		
		<!-- END:		blockUI -->	
		<div id="fb-root"></div>
	    <script type="text/javascript">
	      window.fbAsyncInit = function() {
	        FB.init({
	          appId      : '<?php echo SITE_FACEBOOK_APP_ID; ?>',
	          xfbml      : true,
	          version    : 'v2.0'
	        });
	      };
	      (function(d, s, id){
	         var js, fjs = d.getElementsByTagName(s)[0];
	         if (d.getElementById(id)) {return;}
	         js = d.createElement(s); js.id = id;
	         js.src = "//connect.facebook.net/en_US/sdk.js";
	         fjs.parentNode.insertBefore(js, fjs);
	       }(document, 'script', 'facebook-jssdk'));
	    </script>		
		
        <?php echo $this->partial('partials/header/navbar.phtml'); ?>
		
	    <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2" style="padding-bottom: 10px;">
                    <div style="position: relative;">
                        <div>
                            <img class="avatar-sm img-responsive" src="<?php echo $_SESSION['user']['avatar_url']; ?>">
                        </div>
                        
                        <div style="position: absolute; top: 0; left: 42px;">
                            <div style="font-size: small;">
                                <?php echo $_SESSION['user']['first_name']; ?> <?php echo $_SESSION['user']['last_name']; ?>
                            </div>
                            
                            <div style="font-size: x-small;">
                                <?php echo $_SESSION['user']['email']; ?>
                            </div>
                        </div>                      
                    </div>                                       
                </div>
                
                <div class="col-lg-8"> 
                    <div class="well"> 
                        <form role="form" class="form-horizontal">
                            <div class="form-group" style="padding: 14px;">
                                <textarea class="form-control" rows="5" id="frmNewStatus" name="status" placeholder="<?php echo translate('prompt_whats_new'); ?>"></textarea>
                            </div>
                            
                            <div class="row">
                                <div class="col-lg-6">
                                    <!-- ul class="list-inline">
                                        <li>
                                            <a href="">
                                                <i class="glyphicon glyphicon-upload"></i>
                                            </a>
                                        </li>
                                        
                                        <li>
                                            <a href="">
                                                <i class="glyphicon glyphicon-camera"></i>
                                            </a>
                                        </li>
                                        
                                        <li>
                                            <a href="">
                                                <i class="glyphicon glyphicon-map-marker"></i>
                                            </a>
                                        </li>
                                    </ul -->
                                </div>
                                                            
                                <div class="col-lg-6">
                                    <button class="btn btn-primary pull-right" id="btnNewStatus" type="button">
                                        <i class="fa fa-pencil"></i> <?php echo translate('post'); ?>
                                    </button>                                
                                </div>                            
                            </div>
                        </form>
                    </div> 
                    
                    <div id="statusList"></div>                                 
                </div> 
                
                <!-- START:     Sidebar (Right) -->
                <div class="col-lg-2">
                    <?php echo $this->partial('partials/sidebar/right.phtml'); ?>                                                           
                </div>   
                <!-- END:       Sidebar (Right) -->
                                            
            </div>
        </div>
	    
		<script type="text/javascript">
		    $(document).ready(function() {

		    	// scrollUp
		        $.scrollUp({
		            scrollName: 'scrollUp',      // Element ID
		            scrollDistance: 300,         // Distance from top/bottom before showing element (px)
		            scrollFrom: 'top',           // 'top' or 'bottom'
		            scrollSpeed: 300,            // Speed back to top (ms)
		            easingType: 'linear',        // Scroll to top easing (see http://easings.net/)
		            animation: 'fade',           // Fade, slide, none
		            animationSpeed: 200,         // Animation speed (ms)
		            scrollTrigger: false,        // Set a custom triggering element. Can be an HTML string or jQuery object
		            scrollTarget: false,         // Set a custom target element for scrolling to. Can be element or number
		            scrollText: 'Scroll to top', // Text for element, can contain HTML
		            scrollTitle: false,          // Set a custom <a> title if required.
		            scrollImg: true,            // Set true to use image
		            activeOverlay: false,        // Set CSS color to display scrollUp active point, e.g '#00FFFF'
		            zIndex: 2147483647           // Z-Index for the overlay                    
		        });
		        
				// image preloading    							    		    		   			     			   
				$.imgpreload([
					BASEURL + '/images/preloader/168.gif'
					], {
				    each: function() {
				        // this = dom image object
				        // check for success with: $(this).data('loaded')
				        // callback executes on every image load
				    },
				    all: function() {
				        // this = array of dom image objects
				        // check for success with: $(this[i]).data('loaded')
				        // callback executes when all images are loaded				    		    			    			        
				    }
				});
                
                <?php 
                    if( !empty( $this->messages ) ) {
                        $json = json_encode( $this->messages, true ); 
                ?>
					var template	= $.templates('#templateStatus');
					var htmlOutput	= template.render( <?php echo $json; ?> );

					$('#statusList').html( htmlOutput );
					                
                <?php
                    }
                ?> 										
						    
				$('body').imagesLoaded( function() {
					$.unblockUI();
				});
																				    
		    });	
		    	    				    
			// Google+
		  	(function() {
		    	var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    	po.src = 'https://apis.google.com/js/plusone.js?onload=googleplus_callback_onload';
		    	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  	})(); 		    		    				    
		</script>
		
		<!-- SmartMenus jQuery plugin -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.js"></script>
		
		<!-- SmartMenus jQuery Bootstrap Addon -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.bootstrap.js"></script>
		
		<!-- Bootbox -->							
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootbox/bootbox.js"></script>
		
		<!-- jRumble -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.jrumble.min.js"></script>
		
	    <!-- JsRender -->	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jsrender/jsrender.min.js"></script>		
		
		<!-- OpenFace -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/openface.js"></script>
		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/moment/moment.min.js"></script>
        <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/livestamp.js"></script>
		
	    <?php
	        switch( $currentTheme ) {
	            case 'faceboot':
	    ?>
	    
	    <!-- Custom JS (Faceboot) -->	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/faceboot/extensions.min.js"></script>
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/faceboot/app.min.js"></script> 
	    
	    <?php
	                break;
	        }
	    ?>	
	    
	    <!-- START:    Templates -->
	    <script id="templateStatus" type="text/x-jsrender">
            <div id="statusContainer-{{:id}}" class="panel panel-default">
                <div class="panel-heading">
                    <div class="dropdown pull-right">
                        <a id="statusAction-{{:id}}" data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <i class="fa fa-angle-down"></i>
                        </a> 

                        <ul class="dropdown-menu" role="menu" aria-labelledby="statusAction-{{:id}}">
                            <li role="presentation">
                                <a class="actionStatus" data-action="delete" data-id="{{:id}}" role="menuitem" tabindex="-1" href="#"><?php echo translate('delete'); ?></a>
                            </li>

                            <li role="presentation" class="divider"></li>

                            <li role="presentation">
                                <a class="actionStatus" data-action="edit" data-id="{{:id}}" role="menuitem" tabindex="-1" href="#"><?php echo translate('edit'); ?></a>
                            </li>
                        </ul>
                    </div>

                    <h4>{{:owner.first_name}} {{:owner.last_name}}</h4>

                    <i class="fa fa-clock-o"></i> 
                    <span data-livestamp="{{:date}}">
                        <img src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/preloader/action.png" border="0">
                    </span>
                </div>

                <div class="panel-body">
                    <img class="avatar-md img-circle pull-right" src="{{:owner.avatar_url}}"> 

                    <div id="statusText-{{:id}}">
                        {{:status}}
                    </div>

                    <div class="clearfix"></div>

                    <hr>

                    <p>
                        {{if has_liked}}
                            <a href="#" class="linkUnlike" data-id="{{:id}}" data-uuid="{{:uuid}}"><?php echo translate('unlike'); ?></a>
                        {{else}}
                            <a href="#" class="linkLike" data-id="{{:id}}" data-uuid="{{:uuid}}"><?php echo translate('like'); ?></a>
                        {{/if}}                        
                        &bull; 
                        <a href="#" class="linkComment" data-id="{{:id}}" data-uuid="{{:uuid}}"><?php echo translate('comment'); ?></a>
                    </p>
                    
                    <hr>

                    {{if like_data.count > 0 }}
                        <div class="likeBlock">
                            {{if like_data.count == 1 && has_liked}}
                                <i class="fa fa-thumbs-o-up"></i> <?php echo translate('you_like_this'); ?>
                            {{else like_data.count == 1}}
                                <i class="fa fa-thumbs-o-up"></i> {{:like.data.users[0]['name']}} <?php echo translate('likes_this'); ?>
                            {{else has_liked}}
                                <i class="fa fa-thumbs-o-up"></i> <?php echo translate('you'); ?>, 
                                {{for like_data.users}}				                    
				                    {{:name}}, 
                                {{/for}}
                            {{else}}
                                <i class="fa fa-thumbs-o-up"></i>  
                                {{for like_data.users}}				                    
				                    {{:name}}, 
                                {{/for}}
                                <?php echo translate('you_like_this'); ?>
                            {{/if}}
                        </div>
                    {{/if}}
                        
                    <form id="frmStatusResponse-{{:id}}" name="frmStatusResponse-{{:id}}" role="form">
                        <div class="form-group">
                            <input id="inputStatusResponse-{{:id}}" name="inputStatusResponse-{{:id}}" class="form-control" type="text" placeholder="<?php echo translate('prompt_write_comment'); ?>...">
                            <p class="help-block"><?php echo translate('status_reply_help'); ?></p>
                        </div>

                        <!-- div class="input-group">
                            <input id="inputStatusResponse-{{:id}}" class="form-control" type="text" placeholder="<?php echo translate('prompt_write_comment'); ?>...">
                            <div class="input-group-btn">
                                <button class="btn btn-default">
                                    <i class="fa fa-camera"></i>
                                </button>

                                <button class="btn btn-default">
                                    <i class="fa fa-smile-o"></i>
                                </button>
                            </div>
                        </div -->
                    </form>                                    
                </div>
            </div>
        </script>
        
        <script id="templateNotifyImage" type="text/x-jsrender">
        	<img id="notifyImage-{{:id}}" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/preloader/action.png" border="0">
        </script>	    
	    <!-- END:      Templates -->

        <!-- Q -->	   
        <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/q.min.js"></script>
                
	    <!-- scrollUp -->
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/scrollUp/jquery.scrollUp.min.js"></script>
	    
	    <!-- jsTimezoneDetect -->
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jstz-1.0.4.min.js"></script>
	
        <!-- Bootstrap Datepicker -->	   
        <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>	    			    
	</body>	
</html>