<!DOCTYPE html>
<html>
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <title><?php echo SITE_NAME; ?></title>
	    
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	    <meta name="apple-mobile-web-app-capable" content="yes" />	    

	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/html5shiv.js"></script>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/respond.min.js"></script>
		<![endif]-->	      	    
	    
	 	<?php
			if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ) {
	 			$currentTheme = ( strlen( @$_COOKIE['theme'] ) ) ? $_COOKIE['theme'] : SITE_DEFAULT_TEMPLATE;
			} else {
	 			$currentTheme = SITE_DEFAULT_TEMPLATE;
	 			setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
			}
			
			$_SESSION['current_theme'] = $currentTheme;
		?> 
		
		<?php $siteThemes		= $GLOBALS['SITE_THEMES']; ?>
		<?php $bootstrapThemes	= $GLOBALS['BOOTSTRAP_THEMES']; ?>    	 
				
		<?php if( !empty( $siteThemes ) ): ?>
			
			<?php 		
				if( $currentTheme != SITE_DEFAULT_TEMPLATE ) {
					if( !array_key_exists( $currentTheme, $siteThemes ) ) {
						$currentTheme = SITE_DEFAULT_TEMPLATE;
						setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
					}
				}
			?>
						
			<script type="text/javascript">	
				var BOOTSTRAP_THEMES	= new Array();	
				var SITE_THEMES			= new Array();
				
				<?php foreach( $siteThemes AS $key => $value ): ?>
					SITE_THEMES['<?php echo $key; ?>'] = '<?php echo $value['display_name']; ?>';	
				<?php endforeach; ?>

				<?php foreach( $bootstrapThemes AS $key => $value ): ?>
					BOOTSTRAP_THEMES['<?php echo $key; ?>'] = '<?php echo $value['display_name']; ?>';
				<?php endforeach; ?>				
			</script>
			<?php else: ?>
			<script type="text/javascript">		
				var BOOTSTRAP_THEMES	= new Array();
				var SITE_THEMES			= new Array();
			</script>			
		<?php endif; ?>
		
	    <?php if( !empty( $_SESSION['site']['phrases'] ) ): ?>    
	    	<script type="text/javascript">
	    		var SITE_PHRASES = new Array();
				<?php foreach( $_SESSION['site']['phrases'] AS $key => $value ): ?>
					SITE_PHRASES['<?php echo $key; ?>'] = '<?php echo addslashes( str_replace( "\r\n", '<br>', $value ) ); ?>';
				<?php endforeach; ?>
	    	</script>
	    <?php endif; ?>	
	    
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/phpjs.js"></script>	    		   	    
		<script type="text/javascript">
			var BASEURL					= '<?php echo PROTOCOL_RELATIVE_URL; ?>';
			var DEFAULT_PRELOADER_IMAGE	= '<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>';
			var CURRENT_THEME 			= '<?php echo $currentTheme; ?>';
			var CURRENT_USERNAME		= '<?php echo $_SESSION['user']['username']; ?>';
			var SITE_NAME				= '<?php echo SITE_NAME; ?>';		
			var CURRENT_USER			= new Array();
			var UUID					= uuid();		
			var USE_BLOCKUI				= <?php echo (int)SITE_USE_BLOCKUI; ?>;
			var IS_MOBILE				= <?php echo (int)IS_MOBILE; ?>;	
					
			<?php foreach( $_SESSION['user'] AS $key => $value ): ?>
				<?php if( !is_array( $value ) ): ?>
				    CURRENT_USER['<?php echo $key; ?>'] = '<?php echo base64_encode( $value ); ?>';
				<?php endif; ?>
			<?php endforeach; ?>
		</script>     
	
	    <meta name="robots" content="noimageindex" />
	    
	    <!-- START:    Favicon -->
	    <link rel="Shortcut Icon" type="image/x-icon" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/favicon.ico" /><base>
        <link rel="apple-touch-icon" sizes="57x57" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/favicon-16x16.png">
        <link rel="manifest" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/favicon/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">	    
	    <!-- END:      Favicon -->
	        
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-1.9.1.min.js"></script>					
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootstrap.min.js"></script>		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.cookie.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-ui-1.9.2.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jstorage.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.imgpreload.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/imagesloaded.pkgd.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.defaults.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.observor.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/custom.js"></script>
		
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/custom.css" type="text/css" />				
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/font-awesome.min.css">
		
		<!-- jQuery UI -->
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/jquery-ui/themes/base/jquery-ui.css">
			    
	    <link rel="stylesheet" id="bootstrapCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/bootstrap.min.css">
        <link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/bootstrap.min.css" rel="stylesheet">									     
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/homepage.css" type="text/css" />	
	    		
		<!-- SmartMenus -->
		<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/extensions/smartmenus/jquery.smartmenus.bootstrap.css" rel="stylesheet">	    
	    
	    <!-- Sticky Footer -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/sticky-footer-navbar.css" type="text/css" />	
	    
	    <!-- Custom CSS -->	
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/newsfeed.css" type="text/css" />	
	    
	    <?php
	        switch( $currentTheme ) {
	            case 'faceboot':
	    ?>
	    
	    <!-- Custom CSS (Faceboot) -->	
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/extensions.min.css" type="text/css" />	
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/app.min.css" type="text/css" />
	    
	    <?php
	                break;
	        }
	    ?>							     
	</head>

	<body>
		<!-- START:		blockUI -->
		<?php if( (int)SITE_USE_BLOCKUI == 1 AND (int)IS_MOBILE != 1 ): ?>
			<div style="display: block" class="blockUI"></div>
			<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(255, 255, 255); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
			<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?></div>
		<?php endif; ?>		
		<!-- END:		blockUI -->	
		<div id="fb-root"></div>
	    <script type="text/javascript">
	      window.fbAsyncInit = function() {
	        FB.init({
	          appId      : '<?php echo SITE_FACEBOOK_APP_ID; ?>',
	          xfbml      : true,
	          version    : 'v2.0'
	        });
	      };
	      (function(d, s, id){
	         var js, fjs = d.getElementsByTagName(s)[0];
	         if (d.getElementById(id)) {return;}
	         js = d.createElement(s); js.id = id;
	         js.src = "//connect.facebook.net/en_US/sdk.js";
	         fjs.parentNode.insertBefore(js, fjs);
	       }(document, 'script', 'facebook-jssdk'));
	    </script>		
		
        <?php echo $this->partial('partials/header/navbar.phtml'); ?>
		
	    <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2">
                    <img class="img-thumbnail img-responsive" src="<?php echo $_SESSION['user']['avatar_url']; ?>">
                    <div class="self-username">
                        <strong>
                            <?php echo $_SESSION['user']['username']; ?>
                        </strong>
                        
                        <br>
                        
                        <?php echo translate('edit_profile'); ?>
                    </div>
                </div>
                
                <div class="col-lg-8"> 
                    <div class="well"> 
                        <form role="form" class="form-horizontal">
                            <div class="form-group" style="padding: 14px; padding-top: 0px;">
                                <textarea class="form-control" rows="5" id="frmNewStatus" name="status" placeholder="<?php echo translate('prompt_whats_new'); ?>"></textarea>
                            </div>
                            <button type="button" class="btn btn-lg btn-primary pull-right"><?php echo translate('post'); ?></button>
                            <ul class="list-inline">
                                <li>
                                    <a href="">
                                        <i class="glyphicon glyphicon-upload"></i>
                                    </a>
                                </li>
                                
                                <li>
                                    <a href="">
                                        <i class="glyphicon glyphicon-camera"></i>
                                    </a>
                                </li>
                                
                                <li>
                                    <a href="">
                                        <i class="glyphicon glyphicon-map-marker"></i>
                                    </a>
                                </li>
                            </ul>
                        </form>
                    </div>                                   
                </div> 
                
                <div class="col-lg-2">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pulvinar ut mi sit amet ultricies. Fusce lacinia erat metus, eu consectetur purus egestas sed. Quisque sed porta lacus, et vehicula nibh. Nam maximus fringilla tortor. Etiam sit amet tristique nibh. Nunc ornare lorem vel erat lacinia vulputate. Vestibulum molestie mi vitae ex auctor, quis fermentum mi mollis. Cras ut sollicitudin justo. Sed venenatis dolor lacus, rutrum euismod justo hendrerit sed. Vivamus maximus, ipsum ac viverra tristique, risus diam viverra urna, bibendum congue massa libero eget augue. Integer nec tellus orci.
                    <br><br>
                    Curabitur sit amet elit odio. Proin vel pharetra augue, at tristique justo. Nam faucibus auctor mauris, et tempor turpis malesuada ut. Pellentesque et libero at velit pharetra sagittis. Aliquam aliquet tempor sollicitudin. Donec viverra rhoncus ultricies. Suspendisse tempor risus ac consequat dictum. Donec magna libero, sodales eget fringilla sed, facilisis sed dolor. Ut ac nulla pretium lacus ullamcorper varius et sed nunc. Nullam urna nulla, eleifend sit amet felis hendrerit, suscipit luctus enim. Pellentesque feugiat elementum quam ut faucibus. In hac habitasse platea dictumst. Nam vitae elementum elit. Vivamus non lorem placerat, pellentesque nulla eu, semper tortor. Pellentesque commodo vehicula eros vel pretium.
                    <br><br>
                    Mauris at enim et lacus condimentum blandit. Integer condimentum, nisi sit amet fringilla laoreet, urna ipsum venenatis purus, fermentum porttitor dui tellus eget arcu. Nam risus ante, auctor condimentum sapien vel, volutpat porttitor dolor. Vivamus felis nunc, ultrices commodo ipsum et, tincidunt tincidunt nibh. Nam placerat porta justo vel viverra. Donec ante diam, molestie eu mi at, vehicula posuere tellus. Phasellus sed metus ex. Maecenas quis pellentesque urna, vitae elementum mauris. Proin nec sem posuere, laoreet dui nec, sodales lorem. Praesent at consequat ex. Nunc non justo et risus malesuada eleifend. Integer vulputate eu orci sit amet consequat.
                    <br><br>
                    Quisque in lacus a risus hendrerit tincidunt. Donec non ipsum ipsum. Integer porta placerat tempor. Sed vitae sapien quam. Donec suscipit arcu vel aliquet malesuada. In lobortis blandit nisl, id ornare mauris. Maecenas nec dictum mauris.
                    <br><br>
                    Morbi iaculis nisi eu nunc aliquet, sit amet mollis purus facilisis. Duis eu felis semper, dignissim metus consectetur, maximus tellus. Sed sed est ac quam venenatis ornare. Sed dapibus egestas nibh et gravida. Curabitur ornare, libero rhoncus venenatis consequat, quam ex mattis quam, vitae venenatis lectus dolor in nisl. Vestibulum in ante hendrerit, cursus urna non, finibus lacus. Nullam blandit, felis blandit consectetur scelerisque, lacus tellus condimentum neque, sit amet imperdiet sapien massa id nibh. Maecenas laoreet, mauris sed maximus luctus, augue lorem efficitur mauris, eget molestie lacus justo a velit. Vestibulum lobortis tincidunt urna sit amet pellentesque. Duis dignissim, lorem ac laoreet consequat, nunc leo laoreet eros, nec cursus eros ante at sem. In dictum urna et consectetur posuere. Maecenas nunc dolor, blandit non urna quis, commodo tristique neque.                     
                </div>                               
            </div>
        </div>
	    
		<script type="text/javascript">
		    $(document).ready(function() {	
		    			    				    							    		    		   			     			   
				$.imgpreload([
					BASEURL + '/images/preloader/168.gif'
					], {
				    each: function() {
				        // this = dom image object
				        // check for success with: $(this).data('loaded')
				        // callback executes on every image load
				    },
				    all: function() {
				        // this = array of dom image objects
				        // check for success with: $(this[i]).data('loaded')
				        // callback executes when all images are loaded				    		    			    			        
				    }
				});						
						    
				$('body').imagesLoaded( function() {
					$.unblockUI();
				});																    
		    });	
		    	    				    
			// Google+
		  	(function() {
		    	var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    	po.src = 'https://apis.google.com/js/plusone.js?onload=googleplus_callback_onload';
		    	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  	})(); 		    		    				    
		</script>
		
		<!-- SmartMenus jQuery plugin -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.js"></script>
		
		<!-- SmartMenus jQuery Bootstrap Addon -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.bootstrap.js"></script>
		
		<!-- Bootbox -->							
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootbox/bootbox.js"></script>
		
	    <?php
	        switch( $currentTheme ) {
	            case 'faceboot':
	    ?>
	    
	    <!-- Custom JS (Faceboot) -->	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/faceboot/extensions.min.js"></script>
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/faceboot/app.min.js"></script> 
	    
	    <?php
	                break;
	        }
	    ?>				    
	</body>	
</html>