<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<!-- Apple devices fullscreen -->
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<!-- Apple devices fullscreen -->
	<meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />

	<title><?php echo SITE_NAME; ?> > <?php echo translate('admin', 'ucfirst'); ?> > <?php echo translate('users', 'ucfirst'); ?></title>
	
    <?php if( !empty( $_SESSION['site']['phrases'] ) ): ?>    
    	<script type="text/javascript">
    		var SITE_PHRASES = new Array();
			<?php foreach( $_SESSION['site']['phrases'] AS $key => $value ): ?>
				SITE_PHRASES['<?php echo $key; ?>'] = '<?php echo addslashes( str_replace( "\r\n", '<br>', $value ) ); ?>';
			<?php endforeach; ?>
    	</script>
    <?php endif; ?>		
		    		   	    
	<script type="text/javascript">
		var DATATABLE				= null;
		var BASEURL					= '<?php echo PROTOCOL_RELATIVE_URL; ?>';
		var DEFAULT_PRELOADER_IMAGE	= '<?php echo SITE_DEFAULT_ADMIN_PRELOADER_IMAGE_PATH; ?>';
		var CURRENT_USERNAME		= '<?php echo $_SESSION['user']['username']; ?>';
		var SITE_NAME				= '<?php echo SITE_NAME; ?>';			
		var CURRENT_USER			= new Array();	
				
		<?php foreach( $_SESSION['user'] AS $key => $value ): ?>
			CURRENT_USER['<?php echo $key; ?>'] = '<?php echo $value; ?>';
		<?php endforeach; ?>
	</script>	

	<!-- Bootstrap -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/bootstrap.min.css">
	<!-- Bootstrap responsive -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/bootstrap-responsive.min.css">
	<!-- jQuery UI -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/jquery-ui/themes/redmond/jquery-ui.min.css">
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/jquery-ui/themes/redmond/jquery.ui.theme.css">
	<!-- dataTables -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/plugins/datatable/TableTools.css">
	<!-- chosen -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/plugins/chosen/chosen.css">
	<!-- Theme CSS -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/style.css">
	<!-- Color CSS -->
	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/themes.css">

	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/phpjs.js?<?php echo rand(); ?>"></script>
	<!-- jQuery -->
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-1.8.3.min.js"></script>
	<!-- Bootstrap -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/bootstrap.min.js"></script>	
	
	<!-- Nice Scroll -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/nicescroll/jquery.nicescroll.min.js"></script>
	
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.imgpreload.min.js"></script>
	<!-- imagesLoaded -->
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/imagesLoaded/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/img-preload.js?<?php echo rand(); ?>"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.js"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/jquery.blockUI.defaults.js?<?php echo rand(); ?>"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.cookie.js"></script>	
	<!-- jQuery UI -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.core.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.widget.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.mouse.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.resizable.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.sortable.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/jquery-ui/jquery.ui.datepicker.min.js"></script>
	<!-- slimScroll -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/slimscroll/jquery.slimscroll.min.js"></script>
	<!-- Bootbox -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/bootbox/jquery.bootbox.js"></script>
	<!-- dataTables -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/jquery.dataTables.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/TableTools.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/ColReorderWithResize.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/ColVis.min.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/jquery.dataTables.columnFilter.js"></script>
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/datatable/jquery.dataTables.grouping.js"></script>
	<!-- Chosen -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/chosen/chosen.jquery.min.js"></script>

	<!-- Theme framework -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/eakroko.min.js"></script>
	<!-- Theme scripts -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/application.js"></script>
	<!-- Just for demonstration -->
	<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/demonstration.min.js"></script>

	<!--[if lte IE 9]>
		<script src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/plugins/placeholder/jquery.placeholder.min.js"></script>
		<script>
			$(document).ready(function() {
				$('input, textarea').placeholder();
			});
		</script>
	<![endif]-->
	
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-ui-1.9.2.custom.min.js"></script>	
	<!-- Favicon -->
	<link rel="shortcut icon" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/favicon.ico" />
	<!-- Apple devices Homescreen icon -->
	<link rel="apple-touch-icon-precomposed" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/apple-touch-icon-precomposed.png" />

	<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/admin/custom.css?<?php echo rand(); ?>">
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/custom.js?<?php echo rand(); ?>"></script>
	<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/admin/jquery.observor.js?<?php echo rand(); ?>"></script>	
	<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/font-awesome.min.css" rel="stylesheet">
</head>

	<?php if( strlen( trim( @$_COOKIE['adminTemplateColor'] ) ) ): ?>
		<body class="theme-<?php echo $_COOKIE['adminTemplateColor']; ?>" data-theme="theme-<?php echo $_COOKIE['adminTemplateColor']; ?>">
	<?php else: ?>
		<body>
	<?php endif; ?>
	
	<?php echo $this->partial('partials/blockui.phtml'); ?>
	
	<div id="navigation">
		<div class="container-fluid">
			<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin" id="brand"><i class="icon-thumbs-up-alt"></i> <?php echo SITE_NAME; ?></a>
			<a href="#" class="toggle-nav" rel="tooltip" data-placement="bottom" title="Toggle navigation"><i class="icon-reorder"></i></a>
			<ul class="main-nav">
				<li>
					<a href="#" data-toggle="dropdown" class="dropdown-toggle">
						<span><?php echo ucfirst( translate('settings') ); ?></span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin"><?php echo ucfirst( translate('site') ); ?></a>
						</li>
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/phrases"><?php echo ucfirst( translate('phrases') ); ?></a>
						</li>						
					</ul>
				</li>
				<li class="active">
					<a href="#" data-toggle="dropdown" class='dropdown-toggle'>
						<span><?php echo translate('users', 'ucfirst'); ?></span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li class="active">
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/users"><?php echo ucfirst( translate('all') ); ?></a>
						</li>
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/user-add"><?php echo ucfirst( translate('add_user') ); ?></a>
						</li>
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/usergroups"><?php echo ucfirst( translate('usergroups') ); ?></a>
						</li>																														
					</ul>
				</li>
				<li>
					<a href="#" data-toggle="dropdown" class='dropdown-toggle'>
						<span>Media</span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/media"><?php echo ucfirst( translate('all') ); ?></a>
						</li>
					</ul>
				</li>
			</ul>
			<div class="user">
				<ul class="icon-nav">					
					<li class="dropdown colo">
						<a href="#" class='dropdown-toggle' data-toggle="dropdown"><i class="icon-tint"></i></a>
						<ul class="dropdown-menu pull-right theme-colors">
							<li class="subtitle">
								<?php echo translate('template_color'); ?>
							</li>
							<li>
								<span class='red'></span>
								<span class='orange'></span>
								<span class='green'></span>
								<span class="brown"></span>
								<span class="blue"></span>
								<span class='lime'></span>
								<span class="teal"></span>
								<span class="purple"></span>
								<span class="pink"></span>
								<span class="magenta"></span>
								<span class="grey"></span>
								<span class="darkblue"></span>
								<span class="lightred"></span>
								<span class="lightgrey"></span>
								<span class="satblue"></span>
								<span class="satgreen"></span>
							</li>
						</ul>
					</li>
					<li class="dropdown language-select">						 				
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<?php if( $_SESSION['user']['site_language'] == 1 ): ?>	
								<img src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/demo/flags/us.gif" alt="">												
								<span>English (U.S.)</span>
							<?php elseif( $_SESSION['user']['site_language'] == 2 ): ?>
								<img src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/demo/flags/de.gif" alt="">
								<span>Deutsch</span>
							<?php endif; ?>
						</a>
						<ul class="dropdown-menu pull-right">
							<li>
								<a href="#" id="dropdown-langChange" data-langid="<?php if( $_SESSION['user']['site_language'] == 1 ): ?>2<?php elseif( $_SESSION['user']['site_language'] == 2 ): ?>1<?php endif;?>">
									<?php if( $_SESSION['user']['site_language'] == 1 ): ?>	
										<img src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/demo/flags/de.gif" alt="">					
										<span>Deutsch</span>
									<?php elseif( $_SESSION['user']['site_language'] == 2 ): ?>
										<img src="<?php echo PROTOCOL_RELATIVE_URL; ?>/images/admin/demo/flags/us.gif" alt="">
										<span>English (U.S.)</span>
									<?php endif; ?>								
								</a>
							</li>
						</ul>
					</li>
				</ul>
				<div class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $_SESSION['user']['email']; ?> <img class="adminAvatarThumb" src="<?php echo $_SESSION['user']['avatar_url']; ?>" alt=""></a>
					<ul class="dropdown-menu pull-right">
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/profile/edit" target="_blank"><?php echo ucfirst( translate('account_settings') ); ?></a>
						</li>
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/logout"><?php echo translate('logoff'); ?></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid" id="content">
		<div id="left">
			<div class="subnav subnav-hidden">
				<div class="subnav-title">
					<a href="#" class='toggle-subnav'><i class="icon-angle-down"></i><span><?php echo ucfirst( translate('settings') ); ?></span></a>
				</div>
				<ul class="subnav-menu">
					<li>
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/settings"><?php echo ucfirst( translate('site') ); ?></a>
					</li>
					<li>
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/phrases"><?php echo ucfirst( translate('phrases') ); ?></a>
					</li>
				</ul>
			</div>
			
			<div class="subnav">
				<div class="subnav-title">
					<a href="#" class='toggle-subnav'><i class="icon-angle-down"></i><span><?php echo ucfirst( translate('users') ); ?></span></a>
				</div>
				<ul class="subnav-menu">
					<li class="active">
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/users"><?php echo ucfirst( translate('all') ); ?></a>
					</li>
					<li>
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/user-add"><?php echo ucfirst( translate('add_user') ); ?></a>
					</li>
					<li>
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/usergroups"><?php echo ucfirst( translate('usergroups') ); ?></a>
					</li>					
				</ul>
			</div>
			
			<div class="subnav subnav-hidden">
				<div class="subnav-title">
					<a href="#" class='toggle-subnav'><i class="icon-angle-down"></i><span><?php echo ucfirst( translate('media') ); ?></span></a>
				</div>
				<ul class="subnav-menu">
					<li>
						<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/media"><?php echo ucfirst( translate('all') ); ?></a>
					</li>
				</ul>
			</div>
			
		</div>
		<div id="main">
			<div class="container-fluid">
				<div class="page-header">
					<div class="pull-left">
						<h1><?php echo translate('users', 'ucwords'); ?></h1>
					</div>
					<div class="pull-right">
						<ul class="stats">
							<li class='lightred'>
								<i class="icon-calendar"></i>
								<div class="details">
									<span class="big"></span>
									<span></span>
								</div>
							</li>
						</ul>
					</div>
				</div>
				<div class="breadcrumbs">
					<ul>
						<li>
							<a target="_blank" href="<?php echo PROTOCOL_RELATIVE_URL; ?>"><?php echo SITE_NAME; ?></a>
							<i class="icon-angle-right"></i>
						</li>					
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin"><?php echo translate('admin', 'ucfirst'); ?></a>
							<i class="icon-angle-right"></i>
						</li>
						<li>
							<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/admin/users"><?php echo translate('users', 'ucfirst'); ?></a>
						</li>
					</ul>
					<div class="close-bread">
						<a href="#"><i class="icon-remove"></i></a>
					</div>
				</div>
				
				<div class="row-fluid">
					<div class="span12">
						<div class="box box-color box-bordered">
							<div class="box-title">
								<h3><i class="icon-th-list"></i> <?php echo translate('users', 'ucwords'); ?></h3>
							</div>
							<div class="box-content nopadding">
								<table id="tblData" class="table table-hover table-nomargin table-bordered">
									<thead>
										<tr>						
											<th>e-mail</th>
											<th>Username</th>
											<th>Site Language</th>
											<th>Site Status</th>
											<th>Join Date</th>
											<th>Last Upload</th>
											<th>Last Active</th>
											<th>Last Login</th>
											<th>Signup IP</th>
											<th>Last IP</th>											
											<th></th>	
											<th></th>										
											<th class="with-checkbox">
												Edit
												<div style="float: right;">
													<input type="checkbox" name="cbCheckAllFiles" class="cbCheckAllFiles">
												</div>													
											</th>
										</tr>
									</thead>
									<tbody></tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<script type="text/javascript">
		$(document).ready(function() {			 
			/* create an array with the values of all the checkboxes in a column */
			$.fn.dataTableExt.afnSortData['dom-checkbox'] = function  ( oSettings, iColumn ) {
			    return $.map( oSettings.oApi._fnGetTrNodes(oSettings), function (tr, i) {
			        return $('td:eq('+iColumn+') input', tr).prop('checked') ? '1' : '0';
			    } );
			}

			DATATABLE = $('#tblData')
	        .bind('sort', function () { 
	        	$('#tblData_wrapper').block({ 
		        	overlayCSS: { 
	                	backgroundColor: '#FFFFFF', 
	                	opacity:         0.6, 
	                	cursor:          'wait' 
	            	},
	            	message: '<img border="0" src="'+ BASEURL + '/images/preloader/285-black-128x128.gif">'
	            }); 
			})
	        .bind('filter', function () { 
	        	$('#tblData_wrapper').block({ 
		        	overlayCSS: { 
	                	backgroundColor: '#FFFFFF', 
	                	opacity:         0.6, 
	                	cursor:          'wait' 
	            	},
	            	message: '<img border="0" src="'+ BASEURL + '/images/preloader/285-black-128x128.gif">'
	            });
			})
	        .bind('page', function (event, dataTablesObject) { 
				if( datatablesObject._iRecordsTotal == datatablesObject._iRecordsDisplay ) {
				        return false;
			    }
			     
	        	$('#tblData_wrapper').block({ 
		        	overlayCSS: { 
	                	backgroundColor: '#FFFFFF', 
	                	opacity:         0.6, 
	                	cursor:          'wait' 
	            	},
	            	message: '<img border="0" src="'+ BASEURL + '/images/preloader/285-black-128x128.gif">'
	            });
			})
	        .dataTable({
		    'aoColumns': [
                    // e-mail
                    null,
                    // username
                    null,
                    // site language
                    null,
                    // site status
                    null,
                    // join date
                    {'mRender': function ( data, type, full ) {
                      return date('F j, Y <br> H:i:s', data);
                    }},
                    // last upload
                    {'mRender': function ( data, type, full ) {
                      return ( parseInt( data ) > 0 ) ? date('F j, Y <br> H:i:s', data) : '-';
                    }},
                    // last active
                    {'mRender': function ( data, type, full ) {
                      return ( parseInt( data ) > 0 ) ? date('F j, Y <br> H:i:s', data) : '-';
                    }},
                    // last login
                    {'mRender': function ( data, type, full ) {
                      return ( parseInt( data ) > 0 ) ? date('F j, Y <br> H:i:s', data) : '-';
                    }},			
                    // signup IP				  
                    null,
                    // last IP
                    null,
                    // URL slug
                    { 'bSearchable': false,
                    	'bVisible': false 
                    },                    							  
                    // id colomn							  
                    { 'bSearchable': false,
                    	'bVisible': false 
                    },		    
                    // START:	options column                  
                    {	'mDataProp': null,
                    'sClass': 'with-checkbox',
                    'sDefaultContent': '<a data-id="__ID__" data-urlslug="__URL_SLUG__" href="__BASEURL__/__URL_SLUG__" target="_blank" class="btn adminUserView" rel="tooltip" title="View"><i class="icon-search"></i></a>&nbsp;<a data-id="__ID__" href="#" class="btn adminUserEdit" rel="tooltip" title="Edit"><i class="icon-edit"></i></a>&nbsp;<a data-id="__ID__" data-username="__USERNAME__" href="#" class="btn adminUserDelete" rel="tooltip" title="Delete"><i class="icon-remove"></i></a>&nbsp;<div style="float: right;"><input type="checkbox" class="cbDataTables" value="1"></div>',
                    'sWidth': '10%',
                        'mRender': function ( data, type, full ) {
                        	var newData = str_replace('__ID__', full[11], data); 
                        	newData		= str_replace('__URL_SLUG__', full[10], newData)
                        	newData		= str_replace('__BASEURL__', BASEURL, newData);
                        	newData		= str_replace('__USERNAME__', full[1], newData);
                        	
                        	return newData;
                        }								
                    }
                    // END:	options column							  		                      
				],
				aoColumnDefs: [{
					bSortable: false,
				    aTargets: [ -1 ]								
				}],							
				'bProcessing': false,
				'bServerSide': true,
				'sAjaxSource': BASEURL + '/admin/ajax',
				'sServerMethod': 'POST',
			    'fnServerParams': function ( sSource, aoData, fnCallback, oSettings ) {
			    	sSource.push( { 'name': 'method', 'value': 'dataTablesUsers' } );
				},
			    'fnServerData': function ( sSource, aoData, fnCallback, oSettings ) {
					oSettings.jqXHR = $.ajax({
						'dataType': 'json',
						'type': 'POST',
						'url': sSource,
						'data': aoData,
						'complete': function() {
							$('#tblData_wrapper').unblock();
						},
						'success': fnCallback	
			        });
				}															
			});

		    $.imgpreload([
			    BASEURL + '/images/preloader/285-black-128x128.gif'
			    ], {
				each: function() {
    		        // this = dom image object
    		        // check for success with: $(this).data('loaded')
    		        // callback executes on every image load
				},
				all: function() {
    		        // this = array of dom image objects
    		        // check for success with: $(this[i]).data('loaded')
    		        // callback executes when all images are loaded
				}
			});	

		    // sort by e-mail, asc
		    DATATABLE.fnSort( [ [0, 'asc'] ] );	    
		    $('.adminUserEdit').live('click', function(event) {
			    $.blockUI();
			    var userId = $(this).data('id');
			    window.location.href = BASEURL + '/admin/profile/edit/' + userId;
		    });
		    $('.adminUserDelete').live('click', function(event) {
			    var userId		= $(this).data('id');
			    var username	= $(this).data('username');
				var $dialog		= $('<div></div>')
				.html('Are you sure that you want to delete this user ('+ username +')?')
				.dialog({
					title: '<i class="icon-warning-sign"></i> Delete User',
					minWidth: 600,
					minHeight: 200,
					modal: true,
					buttons: {
						'Yes': function() {	                		
							$.ajax({
								type: 'POST',
								url: BASEURL + '/admin/ajax',
								data: { 
									method: 'admin-delete-user', 				
									userId: userId 
								},
								complete: function( jqXHR, textStatus ) {
								},
								success: function( response, textStatus, jqXHRresponse ) {													
									if( response.status == 'OK' ) {
										$.blockUI();
										$('.ui-dialog-content').dialog('close');
										window.location.reload();																							
									} else {
										$('.ui-dialog-content').dialog('close');
									}								
								},
								error: function(  jqXHR, textStatus, errorThrown ) {
								},		
								dataType: 'json'
							});	
						 },
						 Cancel: function() {
							 $(this).dialog('close');
						 }
					},
					open: function() {
						// http://stackoverflow.com/questions/4103964/icons-in-jquery-ui-dialog-title
						$('.ui-dialog .ui-dialog-title .ui-icon').css({
							'float': 'left',
						    'margin-right': '4px'
						});
						// http://stackoverflow.com/a/3393526
		                $('.ui-dialog-buttonpane').
		                    find('button:contains("Cancel")').button({
		                    	icons: {
		                    		primary: 'ui-icon-cancel'
		                    	}
		                });
		                $('.ui-dialog-buttonpane').
	                    	find('button:contains("Yes")').button({
	                    		icons: {
	                    			primary: 'ui-icon-check'
	                    		}
	                    });				                
					}
				});
				$dialog.dialog('open');			    
		    });        
		});	
	</script>	
	
	<?php echo $this->partial('partials/img-preload.phtml'); ?>	
</body>
</html>