<script id="templateComment" type="text/x-jsrender">
    <div id="commentContainer-{{:id}}" class="comment-container">
        <div class="row">
            <div class="col-sm-1 comment-thumbnail-column">
                <div class="img-thumbnail thumbnail comment-thumbnail">
                    {{if author.avatar_url}}
                        <img src="{{:author.avatar_url}}" class="comment-avatar img-responsive user-photo">
                    {{else}}
                        <img src="<?php echo SITE_DEFAULT_AVATAR_URL; ?>" class="comment-avatar img-responsive user-photo">
                    {{/if}}
                </div><!-- /thumbnail -->
            </div><!-- /col-sm-1 -->

            <div class="col-sm-11">
                <div class="panel panel-default comment-panel">
                    <div class="panel-heading comment-panel-heading">
                        <strong>{{:author.first_name}} {{:author.last_name}}</strong> 

                        <div class="dropdown pull-right">
                            <span class="text-muted" data-livestamp="{{:date}}"><i class="fa fa-spinner fa-pulse"></i></span>

                            {{if current_user.uuid == owner.uuid || current_user.uuid == author.uuid}}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-angle-down"></i> 
                            </a>

                            <ul class="dropdown-menu">
                                <li><a class="commentDelete" href="javascript:void(9);" data-id="{{:id}}"><?php echo translate('delete'); ?></a></li>
                            </ul>
                            {{/if}}
                        </div>

                    </div>
                    
                    <div id="commentText-{{:id}}" class="panel-body">
                        {{nltobr:text}}
                    </div><!-- /panel-body -->

                    <div class="clearfix"></div>
            
                    <hr style="display: none;">
    
                    <p style="padding: 10px; display: none;">
                        <?php echo translate('like'); ?> &bull; <?php echo translate('reply'); ?>
                    </p>
    
                    <hr style="display: none;">
            
                    <form style="display: none; padding: 10px;">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button class="btn btn-default">+1</button><button class="btn btn-default"><i class="glyphicon glyphicon-share"></i></button>
                            </div>
                    
                            <input type="text" class="form-control" placeholder="<?php echo translate('add_comment'); ?> ..">
                        </div>
                    </form>
                </div><!-- /panel panel-default -->
            </div><!-- /col-sm-11 -->
        </div>
    </div>
</script>