<!DOCTYPE html>
<html>
	<head>
	    <title><?php echo SITE_NAME; ?> - <?php echo translate('authorize').' '.$this->app['name']; ?></title>
	    <meta charset="UTF-8" />
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	    <meta name="apple-mobile-web-app-capable" content="yes" />	    
	    	    
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/bootswatch.min.css">
	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/html5shiv.js"></script>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/respond.min.js"></script>
		<![endif]-->	      	    
	    
	 	<?php
			if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ) {
	 			$currentTheme = ( strlen( @$_COOKIE['theme'] ) ) ? $_COOKIE['theme'] : SITE_DEFAULT_TEMPLATE;
			} else {
	 			$currentTheme = SITE_DEFAULT_TEMPLATE;
	 			setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
			}  
		?> 
		
		<?php $siteThemes		= $GLOBALS['SITE_THEMES']; ?>
		<?php $bootstrapThemes	= $GLOBALS['BOOTSTRAP_THEMES']; ?>    	 
				
		<?php if( !empty( $siteThemes ) ): ?>
			
			<?php 		
				if( $currentTheme != SITE_DEFAULT_TEMPLATE ) {
					if( !array_key_exists( $currentTheme, $siteThemes ) ) {
						$currentTheme = SITE_DEFAULT_TEMPLATE;
						setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
					}
				}
			?>
						
			<script type="text/javascript">	
				var BOOTSTRAP_THEMES	= new Array();	
				var SITE_THEMES			= new Array();
				
				<?php foreach( $siteThemes AS $key => $value ): ?>
					SITE_THEMES['<?php echo $key; ?>'] = '<?php echo $value; ?>';	
				<?php endforeach; ?>

				<?php foreach( $bootstrapThemes AS $key => $value ): ?>
					BOOTSTRAP_THEMES['<?php echo $key; ?>'] = '<?php echo $value; ?>';
				<?php endforeach; ?>				
			</script>
			<?php else: ?>
			<script type="text/javascript">		
				var BOOTSTRAP_THEMES	= new Array();
				var SITE_THEMES			= new Array();
			</script>			
		<?php endif; ?>
		
	    <?php if( !empty( $_SESSION['site']['phrases'] ) ): ?>    
	    	<script type="text/javascript">
	    		var SITE_PHRASES = new Array();
				<?php foreach( $_SESSION['site']['phrases'] AS $key => $value ): ?>
					SITE_PHRASES['<?php echo $key; ?>'] = '<?php echo addslashes( str_replace( "\r\n", '<br>', $value ) ); ?>';
				<?php endforeach; ?>
	    	</script>
	    <?php endif; ?>	
	    
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/phpjs.js?<?php echo rand(); ?>"></script>	    		   
	    
		<script type="text/javascript">
			var BASEURL					= '<?php echo PROTOCOL_RELATIVE_URL; ?>';
			var DEFAULT_PRELOADER_IMAGE	= '<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>';
			var CURRENT_THEME 			= '<?php echo $currentTheme; ?>';
			var CURRENT_USERNAME		= '<?php echo $_SESSION['user']['username']; ?>';
			var SITE_NAME				= '<?php echo SITE_NAME; ?>';		
			var CURRENT_USER			= new Array();
			var UUID					= uuid();		
			var USE_BLOCKUI				= <?php echo (int)SITE_USE_BLOCKUI; ?>;
			var IS_MOBILE				= <?php echo (int)IS_MOBILE; ?>;	
					
			<?php foreach( $_SESSION['user'] AS $key => $value ): ?>
				CURRENT_USER['<?php echo $key; ?>'] = '<?php echo $value; ?>';
			<?php endforeach; ?>
		</script>     
	
	    <meta name="robots" content="noimageindex" />
	    <link rel="Shortcut Icon" type="image/x-icon" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/favicon.ico" />
	        
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-1.8.3.min.js"></script>	
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootstrap.min.js"></script>
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootswatch.js"></script>		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.cookie.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-ui-1.9.2.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jstorage.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.imgpreload.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/imagesloaded.pkgd.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.defaults.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.observor.js?<?php echo rand(); ?>"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/custom.js?<?php echo rand(); ?>"></script>
		
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/custom.css?<?php echo rand(); ?>" type="text/css" />				
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/font-awesome.min.css">
		
		<!-- jQuery UI -->
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/jquery-ui/themes/jface/jquery-ui.css">
			    
	    <link id="bootstrapCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/bootstrap.min.css" rel="stylesheet"  media="screen">
	    <?php if( $currentTheme != 'bootstrap-with-theme' ): ?>
	    	<link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/bootstrap.min.css" rel="stylesheet">
	    <?php else: ?>
			<link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/bootstrap/bootstrap.min.css" rel="stylesheet">    
	    <?php endif; ?>										     
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/homepage.css" type="text/css" />										     
	</head>

	<body>
		<!-- START:		blockUI -->
		<?php if( (int)SITE_USE_BLOCKUI == 1 AND (int)IS_MOBILE != 1 ): ?>
			<div style="display: block" class="blockUI"></div>
			<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(0, 0, 0); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
			<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><img src="<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>"></div>
		<?php endif; ?>		
		<!-- END:		blockUI -->	
		<div id="fb-root"></div>
	    <script type="text/javascript">
	      window.fbAsyncInit = function() {
	        FB.init({
	          appId      : '<?php echo SITE_FACEBOOK_APP_ID; ?>',
	          xfbml      : true,
	          version    : 'v2.0'
	        });
	      };
	      (function(d, s, id){
	         var js, fjs = d.getElementsByTagName(s)[0];
	         if (d.getElementById(id)) {return;}
	         js = d.createElement(s); js.id = id;
	         js.src = "//connect.facebook.net/en_US/sdk.js";
	         fjs.parentNode.insertBefore(js, fjs);
	       }(document, 'script', 'facebook-jssdk'));
	    </script>		
		
	    <div class="navbar navbar-default navbar-fixed-top">
			<div class="container">
	        	<div class="navbar-header">
					<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>" class="navbar-brand"><i class="fa fa-magic"></i></a>
	          		<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	          		</button>
	        	</div>
	        	<div class="navbar-collapse collapse" id="navbar-main">
	          		<ul class="nav navbar-nav">
			            <?php if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ): ?>        
			            <li class="dropdown">
			              <a id="themes" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('themes');?> <span class="caret"></span></a>
			              <ul aria-labelledby="themes" class="dropdown-menu">
							<li>
								<a id="linkThemeCurrent" href="#" class="changeTheme" data-name="<?php echo strtolower( $currentTheme ); ?>">
									<?php echo ucfirst( $currentTheme ); ?>
								</a>
			              	</li>
			              	<li class="divider"></li>
			              	<?php foreach( $GLOBALS['SITE_THEMES'] AS $key => $value ): ?>
			              		<?php if( strtolower( $value ) != strtolower( $currentTheme ) ): ?>
			                		<li>
			                			<?php if( array_key_exists( $key, $GLOBALS['BOOTSTRAP_THEMES'] ) ): 
			                				$isBootstrap = true;
			                			else:
			                				$isBootstrap = false;
			                			endif; ?>
			                			<a href="#" class="changeTheme <?php echo strtolower( $key ); ?>" data-bootstrap="<?php echo $isBootstrap; ?>" data-name="<?php echo strtolower( $key ); ?>">
			                				<?php echo $value; ?>
										</a>                			
									</li>
								<?php else: ?>
									<li>
			                			<a class="noBlockUI">
			                				<?php echo $value; ?>
										</a>									
									</li>              	
								<?php endif; ?>
			              	<?php endforeach; ?>
			              </ul>
			            </li>
			            <?php endif; ?>
			            			            			            
			            <?php if( (int)SITE_ALLOW_LANGUAGE_CHANGE == 1 ): ?> 
			            	<?php if( !empty( $GLOBALS['SITE_LANGUAGES'] ) ): ?>			            	       
			            		<li class="dropdown">
					              <a id="changeLang" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('language'); ?> <span class="caret"></span></a>
					              <ul aria-labelledby="changeLang" class="dropdown-menu">
									<li>
										<a id="linkLanguageCurrent" href="#" class="changeLang" data-name="<?php echo strtolower( $currentTheme ); ?>">
											<?php $Languages = new Languages; ?>
											<?php echo $Languages->fetchFriendlyNameById( $_SESSION['user']['site_language'] ); ?>
										</a>
					              	</li>
				                		<li class="divider"></li>
						              	<?php foreach( $GLOBALS['SITE_LANGUAGES'] AS $key => $value ): ?>
					                		<li>
					                			<?php if( $value['id'] != $_SESSION['user']['site_language'] ): ?>
						                			<a href="#" class="changeLang" id="changeLang-<?php echo $value['id']; ?>" data-id="<?php echo $value['id']; ?>" data-name="<?php echo $value['iso_3166_1']; ?>">
						                				<?php echo $value['friendly_name']; ?>
													</a>
												<?php else: ?>
													<a class="noBlockUI">
														<?php echo $value['friendly_name']; ?>
													</a>																										
												<?php endif; ?>               			
											</li>              	
						              	<?php endforeach; ?>
			              			</ul>
			            		</li>
			            	<?php endif; ?>			            		
			            <?php endif; ?>			             		             
	          		</ul>
	
	          		<ul class="nav navbar-nav navbar-right">
	          			<?php if( (int)$_SESSION['user']['logged_in'] == 1 ): ?>
	            		<li class="dropdown">
	              			<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-user"><?php if( isset( $_SESSION['user']['external']['network'] ) ):?> <i class="fa fa-<?php echo $_SESSION['user']['external']['network']; ?>"></i> <?php endif;?><?php echo $_SESSION['user']['email']; ?> <span class="caret"></span></a>
	              			<ul class="dropdown-menu" aria-labelledby="dropdown-user">
		            			<li>
		            				<a id="linkLogout" href="<?php PROTOCOL_RELATIVE_URL; ?>/logout"><i class="fa fa-user"></i> <?php echo translate('logout'); ?></a>
		            			</li>
	              			</ul>
	            		</li>	
	            		<?php else: ?>       
            			<li>
            				<a href="<?php PROTOCOL_RELATIVE_URL; ?>/login"><i class="fa fa-user"></i> <?php echo translate('login'); ?></a>
            			</li>	            		
	            		<?php endif; ?>   		
	          		</ul>
	        	</div>
			</div>
		</div>
	
	
	    <div class="container">
		      <div class="page-header" id="banner">
		      
		      	<?php if( !empty( $this->error ) ): ?>
					<div class="row">
						<div class="alert alert-danger" role="alert">
							<?php foreach( $this->error AS $key => $value ): ?>
								<i class="fa fa-exclamation-triangle"></i> <?php echo $value; ?><br>														
							<?php endforeach; ?>
						</div>
					</div>
				<?php else: ?>						      
			     	<div class="row">
			        	<div class="alert alert-info" role="alert">
			        		<i class="fa fa-question"></i>&nbsp;&nbsp;<strong><?php echo $this->app['name']; ?> is requesting access to your account</strong>
			        	</div>
				    	<div class="col-lg-6">
				        	<h1><?php echo $this->app['name']; ?></h1>
				            <p class="lead">				            	
				            	<?php if( !empty( $_GET['scope'] ) ): ?>
				            		Requested Permissions
				            		<ul>
					            		<?php 
					            			$scope = explode( ' ', $_GET['scope'] ); 
					            			foreach( $scope AS $key => $value ) {
										?>
										<li><?php echo translate( $value ); ?></li>
										<?php									
											}
					            		?>
				            		</ul>
				            	<?php endif; ?>
				            </p>
				            
							<div style="margin-top: 50px;">
								<button type="button" class="btn btn-lg btn-default"><i class="fa fa-check"></i> Allow</button>&nbsp;
								<a href="<?php echo $_GET['redirect_uri']; ?>?error=access_denied">
									<button type="button" class="btn btn-lg btn-danger"><i class="fa fa-times-circle"></i> Cancel</button>
								</a>
							</div>				            
				        </div>
				   		<div class="col-lg-6" style="padding: 15px 15px 0 15px;">
				        	<div class="well sponsor">
				        		About <?php echo $this->app['name']; ?>
				        		<br><br>
								<?php echo $this->app['description']; ?>
				            </div>
				         </div>
			        </div>				
				<?php endif; ?>
		      </div>
	
		      <footer>
		        <div class="row">
		          <div class="col-lg-12">
		
		            <ul class="list-unstyled">
		              <li class="pull-right">
		              	<a href="#top" class="backToTop noBlockUI">
		              		<i class="fa fa-chevron-up"></i>
		              	</a>&nbsp;
						<a href="#top" class="backToTop noBlockUI">	              	
							<?php echo translate('to_top'); ?>
		              	</a>
		              </li>
		              <li>
		              	<i class="fa fa-rss-square"></i>&nbsp;<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/rss">RSS</a>
		              </li>
		            </ul>
		            <p>&copy; <?php echo translate('copyright'); ?> <?php echo date('Y'); ?> <?php echo SITE_NAME; ?>. <?php echo translate('all_rights_reserved'); ?>.</p>
		
		          </div>
		        </div>
		
		      </footer>
	
	
	    </div>
	    
		<script type="text/javascript">
		    $(document).ready(function() {							    		    		   			     			   
				$.imgpreload([DEFAULT_PRELOADER_IMAGE, 
							  BASEURL + '/images/preloader/168.gif'
					], {
				    each: function() {
				        // this = dom image object
				        // check for success with: $(this).data('loaded')
				        // callback executes on every image load
				    },
				    all: function() {
				        // this = array of dom image objects
				        // check for success with: $(this[i]).data('loaded')
				        // callback executes when all images are loaded				    		    			    			        
				    }
				});							
						    
				$('body').imagesLoaded( function() {
					$.unblockUI();
				});																    
		    });		    				    
			// Google+
		  	(function() {
		    	var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    	po.src = 'https://apis.google.com/js/plusone.js?onload=googleplus_callback_onload';
		    	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  	})(); 		    		    				    
		</script>			    
	</body>	
</html>