<?php 
$currentTheme = $_SESSION['current_theme'];
?>

<div class="navbar <?php if( $currentTheme == 'faceboot'): ?> navbar-inverse <?php else: ?> navbar-default <?php endif; ?>  navbar-fixed-top">
	<div class="container-fluid">
    	<div class="navbar-header">
			<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>" class="blockUI-trigger navbar-brand" alt="<?php echo SITE_NAME; ?>" title="<?php echo SITE_NAME; ?>"><i class="fa fa-magic"></i></a>
      		<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
        		<span class="icon-bar"></span>
      		</button>
    	</div>
    	<div class="navbar-collapse collapse" id="navbar-main">
      		<ul class="nav navbar-nav sm sm-core">
	            <?php if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ): ?>        
	            <li class="dropdown">
	              <a id="themes" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('themes');?> <span class="caret"></span></a>
	              <ul aria-labelledby="themes" class="dropdown-menu" id="dropdownThemes">
					<li style="position: relative;">
						<a id="linkThemeCurrent" href="#" class="changeTheme" data-name="<?php echo strtolower( $currentTheme ); ?>">
							<?php foreach( $GLOBALS['SITE_THEMES'] AS $key => $value ): ?>
							    <?php if( $value['name'] == $currentTheme ): ?>
							        <?php echo $value['display_name']; break; ?>
							    <?php endif; ?>
							<?php endforeach; ?>
						</a>
	              	</li>
	              	<li class="divider"></li>
	              	<?php foreach( $GLOBALS['SITE_THEMES'] AS $key => $value ): ?>
                		<li>
                			<?php if( array_key_exists( $key, $GLOBALS['BOOTSTRAP_THEMES'] ) ): 
                				$isBootstrap = true;
                			else:
                				$isBootstrap = false;
                			endif; ?>
                			<a href="#" class="changeTheme <?php echo strtolower( $key ); ?>" data-bootstrap="<?php echo $isBootstrap; ?>" data-name="<?php echo strtolower( $key ); ?>">
                				<?php echo $value['display_name']; ?>
							</a>                			
						</li>
	              	<?php endforeach; ?>
	              </ul>
	            </li>
	            <?php endif; ?>
	            			            			            
	            <?php if( (int)SITE_ALLOW_LANGUAGE_CHANGE == 1 ): ?> 
	            	<?php if( !empty( $GLOBALS['SITE_LANGUAGES'] ) ): ?>			            	       
	            		<li class="dropdown">
			              <a id="changeLang" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('language'); ?> <span class="caret"></span></a>
			              <ul aria-labelledby="changeLang" class="dropdown-menu">
							<li>
								<a id="linkLanguageCurrent" href="#" class="changeLang" data-name="<?php echo strtolower( $currentTheme ); ?>">
									<?php $Language = new Language; ?>
									<?php echo $Language->fetchNativeNameById( $_SESSION['user']['site_language'] ); ?>
								</a>
			              	</li>
		                		<li class="divider"></li>
				              	<?php foreach( $GLOBALS['SITE_LANGUAGES'] AS $key => $value ): ?>
			                		<li>
			                			<a href="#" class="changeLang" id="changeLang-<?php echo $value['id']; ?>" data-id="<?php echo $value['id']; ?>" data-name="<?php echo $value['iso_3166_1']; ?>">
			                				<?php echo $value['native_name']; ?>
										</a>              			
									</li>              	
				              	<?php endforeach; ?>
	              			</ul>
	            		</li>
	            	<?php endif; ?>			            		
	            <?php endif; ?>			             		             
      		</ul>

			<!-- START:	Search Form -->
			<form class="navbar-form navbar-left">
            	<input type="text" style="width: 200%;" placeholder="<?php echo translate('search'); ?>" class="form-control col-lg-8">
            </form>
			<!-- END:	Search Form -->

      		<ul class="nav navbar-nav navbar-right">
        		<li class="dropdown">
          			<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-help"> <i class="fa fa-question-circle"></i> <span class="caret"></span></a>
          			<ul class="dropdown-menu" aria-labelledby="dropdown-help">
            			<li>
            				<a id="linkAbout" href="#">
            				    <?php echo translate('about'); ?>
            				</a>
            			</li>
          			</ul>
        		</li>	          		
      			<?php if( (int)$_SESSION['user']['logged_in'] == 1 ): ?>
        		<li class="dropdown">
          			<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-user"><?php if( isset( $_SESSION['user']['external']['network'] ) ):?> <i class="fa fa-<?php echo $_SESSION['user']['external']['network']; ?>"></i> <?php endif;?><?php echo $_SESSION['user']['email']; ?> <span class="caret"></span></a>
          			<ul class="dropdown-menu" aria-labelledby="dropdown-user">
            			<li>
            				<a id="linkLogout" href="<?php PROTOCOL_RELATIVE_URL; ?>/logout"><?php echo translate('logout'); ?></a>
            			</li>
          			</ul>
        		</li>	
        		<?php else: ?>       
    			<li>
    				<a href="<?php PROTOCOL_RELATIVE_URL; ?>/login"><?php echo translate('login'); ?></a>
    			</li>	            		
        		<?php endif; ?>   		
      		</ul>
    	</div>
	</div>
</div>